version: '3.8'

services:
  backend:
    build: .
    container_name: news-feed-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend:ro
    environment:
      - DATABASE_PATH=/app/data/news_feed.db
      - LM_STUDIO_HOST=host.docker.internal
      - LM_STUDIO_PORT=1234
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: nginx:alpine
    container_name: news-feed-frontend
    ports:
      - "3000:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped